name: scmcp
description: An MCP server for scRNA-Seq analysis software with natural language.
project_home: https://github.com/huang-sh/scmcp
documentation_home: https://github.com/huang-sh/scmcp
install:
  pypi: scmcp
tags:
  - single-cell
  - bioinformatics
  - LLM
  - AI
license: BSD-3-Clause
version: v0.1.1
authors:
  - huangsh
test_command: uv run --no-sync pytest
